import '../styles/globals.css'

export const metadata = {
  title: 'Quiz - Teste Conhecimentos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
}
