"use client"

import "../styles/globals.css";

//Redux Store
import store from "@/redux/store";
import { Provider } from "react-redux";

export const metadata = {
  title: "Quiz - Teste Conhecimentos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="pt-BR">
        <body>{children}</body>
      </html>
    </Provider>
  );
}
